### ISSUE TITLE
PBR datasets not Found

### ISSUE THREAD

**Issue by amerssun** [Aleafy/Make_it_Real#5]
global loadsave.cpp:248 findDecoder imread_('data/material_lib/pbr_maps/train/Metal/acg_painted_metal_003/basecolor.png'): can't open/read file: check file path/integrity

I can't open the URL in OpenXLab. When using the HuggingFace datasets URL, we encounter this error.

**Comment by WilliamHaiweiGu** [comment]
The link to OpenXLab is dead, and the Huggingface repository does not really fit the required file structure

**Comment by Aleafy** [comment]
Hello, @amerssun @WilliamHaiweiGu 

Sorry for the delay in responding due to last week's busyness; I have checked and the website's [URL](https://openxlab.org.cn/datasets/YeFang/MatSynth/tree/main) is now accessible.

Also, you can download the data from [huggingface](https://huggingface.co/datasets/gvecchio/MatSynth/blob/main/scripts/download_dataset.py) (use this script to download), since our offered link is a subset of the original data, downloading from Huggingface is okay, and the folder structure does not change much. 

Just make sure that the `train` folder containing the PBR texture maps is included under `data/material_lib/pbr_maps` as shown in the following path format:

<pre>
data
└── material_lib
    └── pbr_maps
        └── train
            ├── Ceremic
            ├── Concrete
            ├── ...
            └── Wood
</pre>

**Comment by WilliamHaiweiGu** [comment]
Thx. You might want to add this graph to `README.md`.

**Comment by Aleafy** [comment]
OK, I'll modify it.
