### ISSUE TITLE
automatically determine the tiling scale

### ISSUE THREAD

**Issue by dengchcs** [Aleafy/Make_it_Real#8]
Hi, thanks for sharing your work! I noticed that most materials in the dataset do not have a corresponding physical size. How would you determine the proper tiling scale when applying the material to the object? On the ambientcg website, we can control this parameter through the sliding bar, but how to do it automatically?
![image](https://github.com/user-attachments/assets/a9c2782d-7d10-4374-a06f-76dc413c9a0b)

**Comment by Aleafy** [comment]
Hi, @dengchcs  

The case you showed is likely applying material properties to the entire object or region with only shape information, which  requires users to precisely refine the tiling scale or adjust the offset and rotation of some textures. In our tasks, while with the initial albedo map, we adopt a region-to-pixel method to generate material maps (see in paper Section 3.2.3). At the region-level stage, we determine the material area corresponding to each part. However, instead of directly cropping the material texture onto the UV map, we use the albedo value of each pixel on texture map to index specific material properties corresponding to the current region. We describe the details and our intuition in Section 3.2.3 and Appendix B.2 of the paper. You can also find an explanation of the code in the [following link](https://github.com/Aleafy/Make_it_Real/blob/a8e93d308127982d91880d1815786326f8a0b220/utils/texture_postprocess.py#L85).

**Comment by dengchcs** [comment]
After carefully reading the paper, I now understand how the scale problem is solved. Many thanks for your explanation!
